version: '3'

services:
  serving:
    build:
      context: .
      dockerfile: ./docker/serving/Dockerfile
    ports:
      - "8500:8500"
    command: --model_config_file=/models/models.config --model_config_file_poll_wait_seconds=3600
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - serving
    ports:
      - "8888:8888"
    working_dir: /app
    command: python web_server.py
